apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidcompetitions-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapidcompetitions
  template:
    metadata:
      labels:
        app: rapidcompetitions
    spec:
      containers:
      - name: rapidcompetitions
        image: sumonk/rapid-competitions:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: app-secrets

